//! Encrypted credential vault. Direct port of src/helper/vault.ts -- this runs as root in production.
//!
//! Directory layout (all 0600/0700, owned by the process running it, which is root in production):
//!   master.key   legacy import only; removed by migration, never generated by current code
//!   device-binding-<id>.key   random secret mixed into the Secure Enclave vault key; a fresh one
//!                             is created per key change (`<id>` is its SHA-256 digest prefix)
//!                             and earlier ones are removed after commit. `device-binding.key`
//!                             (no id) remains readable for vaults written by older versions
//!   vault.enc    JSON encrypted with AES-256-GCM
//!   audit.log    audit log (never contains credential values)
//!   .lock/       write lock (mkdir is atomic), serializing concurrent writes from multiple sessions

mod crypto;
mod error;
mod master_key;
mod types;
mod validate;
mod vault;

pub use error::{Result, VaultError};
pub use master_key::{
    DeviceBinding, EnclaveKey, EnclaveMetadata, MasterKey, MasterKeyMetadata, MasterKeyProvider,
    ProviderId, WrappedMasterKey, DEVICE_BINDING_BYTES,
};
pub use types::{
    BasicAuth, CredentialRecord, HttpConfig, InjectRule, Kind, TestRequest, TypeRecord, VaultData,
    KINDS,
};
pub use validate::{normalize_name, normalize_type, MAX_PROTOCOL_BYTES, MAX_VALUE_LENGTH};
pub use vault::{
    CreateTypeResult, GetResult, ListEntry, ListTypesEntry, ProtectionStatus, SetParams,
    SetProtocolParams, SetResult, Vault,
};
