// Data format for credential templates. Sources (highest priority first):
//   builtin: built-in generic templates (Bearer / Header / Query / Basic)
//   catalog: KeyValet's bundled template library templates/catalog.json (generated by scripts/build-catalog.mjs, shipped with the project)
//   n8n: optional, templates/n8n-catalog.json generated by the user from a local n8n checkout (n8n's license doesn't allow redistribution, so it isn't shipped with the project)
//
// Placeholder syntax: {{fieldName}}, referencing a credential's secret or non-sensitive field; {{value}} means the value of a single-value credential.

export interface TemplateField {
  name: string;
  label: string;
  /** Whether this is a secret (requires dialog input, is encrypted at rest, and is never returned to the agent) */
  secret: boolean;
  required: boolean;
  default?: string | number | boolean;
  description?: string;
  /** Allowed values for an options-type field */
  options?: string[];
}

/** Rule for injecting a credential into an HTTP request */
export interface InjectRule {
  headers?: Record<string, string>;
  query?: Record<string, string>;
  basic?: { username: string; password: string };
}

/** Request used to verify that a credential works */
export interface TestRequest {
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD";
  /** Full URL template, e.g. https://api.openai.com/v1/models or {{url}}/models */
  url: string;
  headers?: Record<string, string>;
  query?: Record<string, string>;
}

export interface OAuthTemplate {
  authorization_url: string;
  token_url: string;
  scopes: string[];
  extra_auth_params: Record<string, string>;
  token_auth_method: "client_secret_post" | "client_secret_basic";
}

export interface CredentialTemplate {
  id: string;
  name: string;
  source: "builtin" | "catalog" | "n8n";
  docs?: string;
  /** static: stores a value and can be used for proxy calls; oauth2: authorized via credential_oauth_login */
  kind: "static" | "oauth2";
  fields: TemplateField[];
  inject?: InjectRule;
  test?: TestRequest;
  /** API host(s) hardcoded in the template (when the URL contains field placeholders, it's computed from the field values at setup time) */
  hosts?: string[];
  oauth2?: OAuthTemplate;
}

export const PLACEHOLDER_RE = /\{\{\s*([A-Za-z0-9_]+)\s*\}\}/g;

/** All field names referenced by the template */
export function placeholders(values: Array<string | undefined>): string[] {
  const out = new Set<string>();
  for (const v of values) for (const m of (v ?? "").matchAll(PLACEHOLDER_RE)) out.add(m[1]!);
  return [...out];
}

export function injectStrings(rule: InjectRule | undefined): string[] {
  if (!rule) return [];
  return [
    ...Object.values(rule.headers ?? {}),
    ...Object.values(rule.query ?? {}),
    ...(rule.basic ? [rule.basic.username, rule.basic.password] : []),
  ];
}

/** Built-in generic templates: used for HTTP APIs that don't have a dedicated template */
export const BUILTIN_TEMPLATES: CredentialTemplate[] = [
  {
    id: "bearer",
    name: "Generic Bearer token (Authorization: Bearer <token>)",
    source: "builtin",
    kind: "static",
    fields: [{ name: "token", label: "Token", secret: true, required: true }],
    inject: { headers: { Authorization: "Bearer {{token}}" } },
  },
  {
    id: "header",
    name: "Generic header auth (custom header name, e.g. X-Api-Key)",
    source: "builtin",
    kind: "static",
    fields: [
      { name: "headerName", label: "Header name", secret: false, required: true, default: "X-Api-Key" },
      { name: "key", label: "Key", secret: true, required: true },
    ],
    // The header name comes from the field value; the helper expands it into a fixed rule at setup time
    inject: { headers: { "{{headerName}}": "{{key}}" } },
  },
  {
    id: "query",
    name: "Generic query parameter auth (e.g. ?api_key=...)",
    source: "builtin",
    kind: "static",
    fields: [
      { name: "paramName", label: "Parameter name", secret: false, required: true, default: "api_key" },
      { name: "key", label: "Key", secret: true, required: true },
    ],
    inject: { query: { "{{paramName}}": "{{key}}" } },
  },
  {
    id: "basic",
    name: "Generic HTTP Basic auth (username + password)",
    source: "builtin",
    kind: "static",
    fields: [
      { name: "user", label: "Username", secret: false, required: true },
      { name: "password", label: "Password", secret: true, required: true },
    ],
    inject: { basic: { username: "{{user}}", password: "{{password}}" } },
  },
];
